const DEFAULT=[[526870,"Satisfactory"],[387990,"Scrap Mechanic"],[251570,"7 Days to Die"],[361420,"ASTRONEER"],[552100,"Brick Rigs"],[374320,"DARK SOULS™ III"],[570940,"DARK SOULS™: REMASTERED"],[239140,"Dying Light"],[534380,"Dying Light 2: Reloaded Edition"],[3008130,"Dying Light: The Beast"],[2622380,"ELDEN RING NIGHTREIGN"],[1248130,"Farming Simulator 22"],[451340,"Gold Mining Simulator"],[815370,"Green Hell"],[553850,"HELLDIVERS™ 2"],[4001890,"How to Fish"],[1103730,"Hydroneer"],[516750,"My Summer Car"],[1905180,"OBS Studio"],[2144900,"PAYDAY 3"],[648800,"Raft"],[1144200,"Ready or Not"],[3241660,"R.E.P.O."],[3164500,"Schedule I"],[1326470,"Sons Of The Forest"],[629520,"Soundpad"],[264710,"Subnautica"],[848450,"Subnautica: Below Zero"],[1962700,"Subnautica 2"],[242760,"The Forest"],[518790,"theHunter: Call of the Wild™"],[700330,"SCP: Secret Laboratory"],[227860,"Castle Story"],[1657630,"Slime Rancher 2"],[593600,"PixARK"],[1350650,"FreshWomen - Season 1"],[1465360,"SnowRunner"]].map(x=>({id:String(x[0]),name:x[1]}));
const $=x=>document.getElementById(x),KEY="asf_idle_new";
function safe(){try{return JSON.parse(localStorage.getItem(KEY)||"{}")}catch{return {}}}
let d=safe();let games=Array.isArray(d.games)&&d.games.length?d.games:DEFAULT.map(x=>({...x})),selected=new Set((d.selected||[]).map(String).slice(0,32)),presets=d.presets||[],accounts=d.accounts||[];
const image=id=>`https://cdn.cloudflare.steamstatic.com/steam/apps/${id}/header.jpg`;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function save(){localStorage.setItem(KEY,JSON.stringify({games,selected:[...selected],presets,accounts}))}
function toast(t){$("toast").textContent=t;$("toast").classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>$("toast").classList.remove("show"),1600)}
function cfg(){return `"GamesPlayedWhileIdle": [${[...selected].join(", ")}]`}
async function cp(t){try{await navigator.clipboard.writeText(t);return 1}catch(e){let x=document.createElement("textarea");x.value=t;document.body.appendChild(x);x.select();let ok=false;try{ok=document.execCommand("copy")}catch(e){}x.remove();return ok}}
function renderGames(){let q=$("search").value.toLowerCase(),s=$("sort").value,a=games.filter(g=>g.name.toLowerCase().includes(q)||g.id.includes(q));if(s==="name")a.sort((x,y)=>x.name.localeCompare(y.name));if(s==="id")a.sort((x,y)=>+x.id-+y.id);if(s==="sel")a.sort((x,y)=>Number(selected.has(y.id))-Number(selected.has(x.id)));$("count").textContent=`${a.length} wyników · ${selected.size}/32`;$("grid").innerHTML=a.length?a.map(g=>{let on=selected.has(g.id);return `<button class="game ${on?"selected":""}" data-id="${g.id}"><img src="${image(g.id)}" onerror="this.style.visibility='hidden'"><div><b>${esc(g.name)}</b><small>AppID ${g.id}</small></div><i class="check">${on?"✓":""}</i></button>`}).join(""):`<div class="empty">Brak wyników.</div>`;document.querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>{let id=b.dataset.id;if(selected.has(id))selected.delete(id);else if(selected.size<32)selected.add(id);else return toast("Maksymalnie 32 AppID");render()})}
function render(){ $("sg").textContent=games.length;$("ss").textContent=selected.size;$("sp").textContent=presets.length;$("sa").textContent=accounts.length;$("out").textContent=cfg();let a=games.filter(g=>selected.has(g.id));$("chosen").innerHTML=a.length?a.map(g=>`<div class="mini"><img src="${image(g.id)}"><div><b>${esc(g.name)}</b><small>${g.id}</small></div></div>`).join(""):`<div class="empty">Nie wybrano gier.</div>`;renderGames();renderPresets();renderAccounts();save()}
function renderPresets(){$("presetsList").innerHTML=presets.length?presets.map((p,i)=>`<div class="card"><div><b>${esc(p.name)}</b><small>${p.ids.length} gier</small></div><div class="actions"><button class="small" data-lp="${i}">Wczytaj</button><button class="small" data-dp="${i}">Usuń</button></div></div>`).join(""):`<div class="empty">Brak presetów.</div>`;document.querySelectorAll("[data-lp]").forEach(b=>b.onclick=()=>{selected=new Set(presets[+b.dataset.lp].ids.slice(0,32));render();toast("Preset wczytany")});document.querySelectorAll("[data-dp]").forEach(b=>b.onclick=()=>{presets.splice(+b.dataset.dp,1);render()})}
function renderAccounts(){$("accountsList").innerHTML=accounts.length?accounts.map((a,i)=>`<div class="card"><div><b>${esc(a.name)}</b><small>${a.ids.length} gier</small></div><div class="actions"><button class="small" data-la="${i}">Wczytaj</button><button class="small" data-da="${i}">Usuń</button></div></div>`).join(""):`<div class="empty">Brak profili.</div>`;document.querySelectorAll("[data-la]").forEach(b=>b.onclick=()=>{selected=new Set(accounts[+b.dataset.la].ids.slice(0,32));render();toast("Profil wczytany")});document.querySelectorAll("[data-da]").forEach(b=>b.onclick=()=>{accounts.splice(+b.dataset.da,1);render()})}
function modal(title,body){$("mt").textContent=title;$("mb").innerHTML=body;$("modal").classList.add("open")}
function close(){ $("modal").classList.remove("open") }
document.querySelectorAll(".nav").forEach(n=>n.onclick=()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));n.classList.add("active");document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));$(n.dataset.v).classList.add("active");$("title").textContent=n.textContent.trim()});
$("goGames").onclick=()=>document.querySelector('[data-v="games"]').click();$("search").oninput=renderGames;$("sort").onchange=renderGames;$("close").onclick=close;$("modal").onclick=e=>{if(e.target.id==="modal")close()};
document.querySelectorAll("[data-copy]").forEach(b=>b.onclick=async()=>toast(await cp($(b.dataset.copy).textContent)?"Skopiowano":"Nie udało się skopiować"));
$("quick").onclick=()=>modal("Quick Add",`<div class="form"><label>AppID-y, np. 730, 570, 252490</label><input id="ids" placeholder="730, 570"><div class="form-actions"><button class="ghost" id="cancel">Anuluj</button><button class="primary" id="ok">Dodaj</button></div></div>`);
$("custom").onclick=()=>modal("Własna gra",`<div class="form"><label>Nazwa</label><input id="gn"><label>AppID</label><input id="gi" inputmode="numeric"><div class="form-actions"><button class="ghost" id="cancel">Anuluj</button><button class="primary" id="ok">Dodaj</button></div></div>`);
$("newPreset").onclick=()=>modal("Nowy preset",`<div class="form"><label>Nazwa</label><input id="pn"><div class="form-actions"><button class="ghost" id="cancel">Anuluj</button><button class="primary" id="ok">Zapisz</button></div></div>`);
$("newAccount").onclick=()=>modal("Nowy profil",`<div class="form"><label>Nazwa</label><input id="an"><div class="form-actions"><button class="ghost" id="cancel">Anuluj</button><button class="primary" id="ok">Zapisz</button></div></div>`);
$("mb").onclick=e=>{if(e.target.id==="cancel")close();if(e.target.id==="ok"){let t=$("mt").textContent;if(t==="Quick Add"){for(let id of ($("ids").value.match(/\d+/g)||[])){if(!games.some(g=>g.id===id))games.push({id,name:"Steam App "+id});if(selected.size<32)selected.add(id)}}else if(t==="Własna gra"){let id=$("gi").value.trim(),name=$("gn").value.trim();if(!id||!name)return toast("Podaj nazwę i AppID");if(!games.some(g=>g.id===id))games.push({id,name})}else if(t==="Nowy preset"){let name=$("pn").value.trim();if(!name)return toast("Podaj nazwę");presets.push({name,ids:[...selected]})}else{let name=$("an").value.trim();if(!name)return toast("Podaj nazwę");accounts.push({name,ids:[...selected]})}close();render();toast("Gotowe")}};
$("export").onclick=()=>{let blob=new Blob([JSON.stringify({games,selected:[...selected],presets,accounts},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="asf-idle-backup.json";a.click();URL.revokeObjectURL(a.href);toast("Eksport gotowy")};
$("import").onclick=()=>{let f=$("file").files[0];if(!f)return toast("Wybierz plik JSON");let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!Array.isArray(x.games)||!Array.isArray(x.selected))throw 0;games=x.games;selected=new Set(x.selected.slice(0,32).map(String));presets=Array.isArray(x.presets)?x.presets:[];accounts=Array.isArray(x.accounts)?x.accounts:[];render();toast("Import OK")}catch{toast("Nieprawidłowy JSON")}};r.readAsText(f)};
$("reset").onclick=()=>{if(confirm("Usunąć lokalne dane?")){localStorage.removeItem(KEY);location.reload()}};render();